            CALL GET4(ITEMP,RCMD(5),RCMD(4),RCMD(3),RCMD(2))
            AFILT(1) = FTEMP
            CALL GET4(ITEMP,RCMD(9),RCMD(8),RCMD(7),RCMD(6))
            AFILT(2) = FTEMP
            CALL GET4(ITEMP,RCMD(13),RCMD(12),RCMD(11),RCMD(10))
            AFILT(4) = FTEMP
            CALL GET4(ITEMP,RCMD(17),RCMD(16),RCMD(15),RCMD(14))
            AFILT(3) = FTEMP
            CALL GET4(ITEMP,RCMD(21),RCMD(20),RCMD(19),RCMD(18))
            BSCALE = FTEMP
            CALL GET4(ITEMP,RCMD(25),RCMD(24),RCMD(23),RCMD(22))
            STMAX = FTEMP
